Repository Ninja-Official/rtu-mirea-mobile, pull requests merged in 2021-07, with the labels that each got.

#7 Create onboarding screen
  assets/images/Book1.png
  assets/images/Doge.png
  assets/images/TeachSchedule.png
  ios/Flutter/AppFrameworkInfo.plist
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/main.dart
  lib/screens/home/home_screen.dart
  lib/screens/onBoard/my_shared_preferences.dart
  lib/screens/onBoard/screenBoard.dart
  pubspec.yaml
Labels: enhancement

#9 Add clean architecture with bloc
  CONTRIBUTING.md
  lib/common/calendar.dart
  lib/common/errors/exceptions.dart
  lib/data/datasources/schedule_local.dart
  lib/data/datasources/schedule_remote.dart
  lib/data/models/lesson_model.dart
  lib/data/models/schedule_model.dart
  lib/data/repositories/schedule_repository_impl.dart
  lib/domain/entities/lesson.dart
  lib/domain/entities/schedule.dart
  lib/domain/repositories/schedule_repository.dart
  lib/domain/usecases/get_groups.dart
  lib/domain/usecases/get_schedule.dart
  lib/domain/usecases/is_group_exist.dart
  lib/domain/usecases/usecase.dart
  lib/main.dart
  lib/models/lesson.dart
  lib/presentation/bloc/home_navigator_bloc/home_navigator_bloc.dart
  lib/presentation/bloc/home_navigator_bloc/home_navigator_event.dart
  lib/presentation/bloc/home_navigator_bloc/home_navigator_state.dart
  lib/presentation/colors.dart
  lib/presentation/pages/home/home_navigator_screen.dart
  lib/presentation/pages/onboarding/onboarding_screen.dart
  lib/presentation/pages/schedule/components/app_bar.dart
  lib/presentation/pages/schedule/components/lesson_card.dart
  lib/presentation/pages/schedule/components/schedule_page_view.dart
  lib/presentation/pages/schedule/schedule_screen.dart
  lib/presentation/pages/settings/group_selection_screen.dart
  lib/presentation/pages/settings/settings_screen.dart
  lib/presentation/theme.dart
  lib/presentation/widgets/settings_button.dart
  lib/screens/home/home_screen.dart
  lib/utils/schedule.dart
  pubspec.yaml
Labels: enhancement

#10 Better calendar
  lib/common/calendar.dart
  lib/presentation/pages/schedule/components/schedule_page_view.dart
  test/calendar_test.dart
  test/mirea_test.dart
Labels: bug, documentation

#19 REFACTOR: Improve onboarding
  lib/common/constants.dart
  lib/data/datasources/onboarding_data.dart
  lib/data/repositories/onboarding_repository.dart
  lib/domain/entities/onboarding_page.dart
  lib/domain/repositories/onboarding_repository.dart
  lib/domain/usecases/onboarding/get_page.dart
  lib/main.dart
  lib/presentation/bloc/onboarding_cubit.dart
  lib/presentation/pages/onboarding/onboarding_screen.dart
  lib/service_locator.dart
  test/mirea_test.dart
  test/utils/calendar_test.dart
  test/widgets/onboarding_test.dart
Labels: documentation
